// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DualStickRawInputCommandBuffer.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Redhatgamedev.Srt {

  /// <summary>Holder for reflection information generated from DualStickRawInputCommandBuffer.proto</summary>
  public static partial class DualStickRawInputCommandBufferReflection {

    #region Descriptor
    /// <summary>File descriptor for DualStickRawInputCommandBuffer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DualStickRawInputCommandBufferReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiREdWFsU3RpY2tSYXdJbnB1dENvbW1hbmRCdWZmZXIucHJvdG8SEXJlZGhh",
            "dGdhbWVkZXYuc3J0Ggtib3gyZC5wcm90byJjCh5EdWFsU3RpY2tSYXdJbnB1",
            "dENvbW1hbmRCdWZmZXISHwoIcGJ2Mk1vdmUYASACKAsyDS5ib3gyZC5QYlZl",
            "YzISIAoJcGJ2MlNob290GAIgAigLMg0uYm94MmQuUGJWZWMy"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Box2D.Box2DReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Redhatgamedev.Srt.DualStickRawInputCommandBuffer), global::Redhatgamedev.Srt.DualStickRawInputCommandBuffer.Parser, new[]{ "Pbv2Move", "Pbv2Shoot" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class DualStickRawInputCommandBuffer : pb::IMessage<DualStickRawInputCommandBuffer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DualStickRawInputCommandBuffer> _parser = new pb::MessageParser<DualStickRawInputCommandBuffer>(() => new DualStickRawInputCommandBuffer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DualStickRawInputCommandBuffer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Redhatgamedev.Srt.DualStickRawInputCommandBufferReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DualStickRawInputCommandBuffer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DualStickRawInputCommandBuffer(DualStickRawInputCommandBuffer other) : this() {
      pbv2Move_ = other.pbv2Move_ != null ? other.pbv2Move_.Clone() : null;
      pbv2Shoot_ = other.pbv2Shoot_ != null ? other.pbv2Shoot_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DualStickRawInputCommandBuffer Clone() {
      return new DualStickRawInputCommandBuffer(this);
    }

    /// <summary>Field number for the "pbv2Move" field.</summary>
    public const int Pbv2MoveFieldNumber = 1;
    private global::Box2D.PbVec2 pbv2Move_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Box2D.PbVec2 Pbv2Move {
      get { return pbv2Move_; }
      set {
        pbv2Move_ = value;
      }
    }

    /// <summary>Field number for the "pbv2Shoot" field.</summary>
    public const int Pbv2ShootFieldNumber = 2;
    private global::Box2D.PbVec2 pbv2Shoot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Box2D.PbVec2 Pbv2Shoot {
      get { return pbv2Shoot_; }
      set {
        pbv2Shoot_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DualStickRawInputCommandBuffer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DualStickRawInputCommandBuffer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Pbv2Move, other.Pbv2Move)) return false;
      if (!object.Equals(Pbv2Shoot, other.Pbv2Shoot)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (pbv2Move_ != null) hash ^= Pbv2Move.GetHashCode();
      if (pbv2Shoot_ != null) hash ^= Pbv2Shoot.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (pbv2Move_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Pbv2Move);
      }
      if (pbv2Shoot_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Pbv2Shoot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (pbv2Move_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Pbv2Move);
      }
      if (pbv2Shoot_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Pbv2Shoot);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (pbv2Move_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pbv2Move);
      }
      if (pbv2Shoot_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pbv2Shoot);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DualStickRawInputCommandBuffer other) {
      if (other == null) {
        return;
      }
      if (other.pbv2Move_ != null) {
        if (pbv2Move_ == null) {
          Pbv2Move = new global::Box2D.PbVec2();
        }
        Pbv2Move.MergeFrom(other.Pbv2Move);
      }
      if (other.pbv2Shoot_ != null) {
        if (pbv2Shoot_ == null) {
          Pbv2Shoot = new global::Box2D.PbVec2();
        }
        Pbv2Shoot.MergeFrom(other.Pbv2Shoot);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (pbv2Move_ == null) {
              Pbv2Move = new global::Box2D.PbVec2();
            }
            input.ReadMessage(Pbv2Move);
            break;
          }
          case 18: {
            if (pbv2Shoot_ == null) {
              Pbv2Shoot = new global::Box2D.PbVec2();
            }
            input.ReadMessage(Pbv2Shoot);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (pbv2Move_ == null) {
              Pbv2Move = new global::Box2D.PbVec2();
            }
            input.ReadMessage(Pbv2Move);
            break;
          }
          case 18: {
            if (pbv2Shoot_ == null) {
              Pbv2Shoot = new global::Box2D.PbVec2();
            }
            input.ReadMessage(Pbv2Shoot);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
