// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EntityGameEventBuffer.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Redhatgamedev.Srt {

  /// <summary>Holder for reflection information generated from EntityGameEventBuffer.proto</summary>
  public static partial class EntityGameEventBufferReflection {

    #region Descriptor
    /// <summary>File descriptor for EntityGameEventBuffer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityGameEventBufferReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtFbnRpdHlHYW1lRXZlbnRCdWZmZXIucHJvdG8SEXJlZGhhdGdhbWVkZXYu",
            "c3J0Ggtib3gyZC5wcm90byKNAgoVRW50aXR5R2FtZUV2ZW50QnVmZmVyElkK",
            "BHR5cGUYASACKA4yQi5yZWRoYXRnYW1lZGV2LnNydC5FbnRpdHlHYW1lRXZl",
            "bnRCdWZmZXIuRW50aXR5R2FtZUV2ZW50QnVmZmVyVHlwZToHVU5LTk9XThIR",
            "CgllbnRpdHlUYWcYAiACKAQSDAoEVVVJRBgDIAEoCRIbCgRib2R5GAQgASgL",
            "Mg0uYm94MmQuUGJCb2R5IlsKGUVudGl0eUdhbWVFdmVudEJ1ZmZlclR5cGUS",
            "CwoHVU5LTk9XThAAEgoKBkNSRUFURRABEgwKCFJFVFJJRVZFEAISCgoGVVBE",
            "QVRFEAMSCwoHREVTVFJPWRAE"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Box2D.Box2DReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Redhatgamedev.Srt.EntityGameEventBuffer), global::Redhatgamedev.Srt.EntityGameEventBuffer.Parser, new[]{ "Type", "EntityTag", "UUID", "Body" }, null, new[]{ typeof(global::Redhatgamedev.Srt.EntityGameEventBuffer.Types.EntityGameEventBufferType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EntityGameEventBuffer : pb::IMessage<EntityGameEventBuffer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EntityGameEventBuffer> _parser = new pb::MessageParser<EntityGameEventBuffer>(() => new EntityGameEventBuffer());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EntityGameEventBuffer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Redhatgamedev.Srt.EntityGameEventBufferReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityGameEventBuffer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityGameEventBuffer(EntityGameEventBuffer other) : this() {
      _hasBits0 = other._hasBits0;
      type_ = other.type_;
      entityTag_ = other.entityTag_;
      uUID_ = other.uUID_;
      body_ = other.body_ != null ? other.body_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EntityGameEventBuffer Clone() {
      return new EntityGameEventBuffer(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private readonly static global::Redhatgamedev.Srt.EntityGameEventBuffer.Types.EntityGameEventBufferType TypeDefaultValue = global::Redhatgamedev.Srt.EntityGameEventBuffer.Types.EntityGameEventBufferType.Unknown;

    private global::Redhatgamedev.Srt.EntityGameEventBuffer.Types.EntityGameEventBufferType type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Redhatgamedev.Srt.EntityGameEventBuffer.Types.EntityGameEventBufferType Type {
      get { if ((_hasBits0 & 1) != 0) { return type_; } else { return TypeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        type_ = value;
      }
    }
    /// <summary>Gets whether the "type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasType {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearType() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "entityTag" field.</summary>
    public const int EntityTagFieldNumber = 2;
    private readonly static ulong EntityTagDefaultValue = 0UL;

    private ulong entityTag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong EntityTag {
      get { if ((_hasBits0 & 2) != 0) { return entityTag_; } else { return EntityTagDefaultValue; } }
      set {
        _hasBits0 |= 2;
        entityTag_ = value;
      }
    }
    /// <summary>Gets whether the "entityTag" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEntityTag {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "entityTag" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEntityTag() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "UUID" field.</summary>
    public const int UUIDFieldNumber = 3;
    private readonly static string UUIDDefaultValue = "";

    private string uUID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UUID {
      get { return uUID_ ?? UUIDDefaultValue; }
      set {
        uUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "UUID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUUID {
      get { return uUID_ != null; }
    }
    /// <summary>Clears the value of the "UUID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUUID() {
      uUID_ = null;
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 4;
    private global::Box2D.PbBody body_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Box2D.PbBody Body {
      get { return body_; }
      set {
        body_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EntityGameEventBuffer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EntityGameEventBuffer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (EntityTag != other.EntityTag) return false;
      if (UUID != other.UUID) return false;
      if (!object.Equals(Body, other.Body)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasType) hash ^= Type.GetHashCode();
      if (HasEntityTag) hash ^= EntityTag.GetHashCode();
      if (HasUUID) hash ^= UUID.GetHashCode();
      if (body_ != null) hash ^= Body.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (HasEntityTag) {
        output.WriteRawTag(16);
        output.WriteUInt64(EntityTag);
      }
      if (HasUUID) {
        output.WriteRawTag(26);
        output.WriteString(UUID);
      }
      if (body_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Body);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (HasEntityTag) {
        output.WriteRawTag(16);
        output.WriteUInt64(EntityTag);
      }
      if (HasUUID) {
        output.WriteRawTag(26);
        output.WriteString(UUID);
      }
      if (body_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Body);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (HasEntityTag) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(EntityTag);
      }
      if (HasUUID) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UUID);
      }
      if (body_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Body);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EntityGameEventBuffer other) {
      if (other == null) {
        return;
      }
      if (other.HasType) {
        Type = other.Type;
      }
      if (other.HasEntityTag) {
        EntityTag = other.EntityTag;
      }
      if (other.HasUUID) {
        UUID = other.UUID;
      }
      if (other.body_ != null) {
        if (body_ == null) {
          Body = new global::Box2D.PbBody();
        }
        Body.MergeFrom(other.Body);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Redhatgamedev.Srt.EntityGameEventBuffer.Types.EntityGameEventBufferType) input.ReadEnum();
            break;
          }
          case 16: {
            EntityTag = input.ReadUInt64();
            break;
          }
          case 26: {
            UUID = input.ReadString();
            break;
          }
          case 34: {
            if (body_ == null) {
              Body = new global::Box2D.PbBody();
            }
            input.ReadMessage(Body);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Redhatgamedev.Srt.EntityGameEventBuffer.Types.EntityGameEventBufferType) input.ReadEnum();
            break;
          }
          case 16: {
            EntityTag = input.ReadUInt64();
            break;
          }
          case 26: {
            UUID = input.ReadString();
            break;
          }
          case 34: {
            if (body_ == null) {
              Body = new global::Box2D.PbBody();
            }
            input.ReadMessage(Body);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the EntityGameEventBuffer message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum EntityGameEventBufferType {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("CREATE")] Create = 1,
        [pbr::OriginalName("RETRIEVE")] Retrieve = 2,
        [pbr::OriginalName("UPDATE")] Update = 3,
        [pbr::OriginalName("DESTROY")] Destroy = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
