// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameEventBuffer.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Redhatgamedev.Srt {

  /// <summary>Holder for reflection information generated from GameEventBuffer.proto</summary>
  public static partial class GameEventBufferReflection {

    #region Descriptor
    /// <summary>File descriptor for GameEventBuffer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameEventBufferReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVHYW1lRXZlbnRCdWZmZXIucHJvdG8SEXJlZGhhdGdhbWVkZXYuc3J0GhtF",
            "bnRpdHlHYW1lRXZlbnRCdWZmZXIucHJvdG8iKwobSm9pblNlY3VyaXR5R2Ft",
            "ZUV2ZW50QnVmZmVyEgwKBFVVSUQYASACKAkiLAocTGVhdmVTZWN1cml0eUdh",
            "bWVFdmVudEJ1ZmZlchIMCgRVVUlEGAEgAigJIuUCChdTZWN1cml0eUdhbWVF",
            "dmVudEJ1ZmZlchJdCgR0eXBlGAEgAigOMkYucmVkaGF0Z2FtZWRldi5zcnQu",
            "U2VjdXJpdHlHYW1lRXZlbnRCdWZmZXIuU2VjdXJpdHlHYW1lRXZlbnRCdWZm",
            "ZXJUeXBlOgdVTktOT1dOElMKG2pvaW5TZWN1cml0eUdhbWVFdmVudEJ1ZmZl",
            "chgDIAEoCzIuLnJlZGhhdGdhbWVkZXYuc3J0LkpvaW5TZWN1cml0eUdhbWVF",
            "dmVudEJ1ZmZlchJVChxsZWF2ZVNlY3VyaXR5R2FtZUV2ZW50QnVmZmVyGAQg",
            "ASgLMi8ucmVkaGF0Z2FtZWRldi5zcnQuTGVhdmVTZWN1cml0eUdhbWVFdmVu",
            "dEJ1ZmZlciI/ChtTZWN1cml0eUdhbWVFdmVudEJ1ZmZlclR5cGUSCwoHVU5L",
            "Tk9XThAAEggKBEpPSU4QARIJCgVMRUFWRRACIrQCCg9HYW1lRXZlbnRCdWZm",
            "ZXISTQoEdHlwZRgBIAIoDjI2LnJlZGhhdGdhbWVkZXYuc3J0LkdhbWVFdmVu",
            "dEJ1ZmZlci5HYW1lRXZlbnRCdWZmZXJUeXBlOgdVTktOT1dOEkcKFWVudGl0",
            "eUdhbWVFdmVudEJ1ZmZlchgCIAEoCzIoLnJlZGhhdGdhbWVkZXYuc3J0LkVu",
            "dGl0eUdhbWVFdmVudEJ1ZmZlchJLChdzZWN1cml0eUdhbWVFdmVudEJ1ZmZl",
            "chgDIAEoCzIqLnJlZGhhdGdhbWVkZXYuc3J0LlNlY3VyaXR5R2FtZUV2ZW50",
            "QnVmZmVyIjwKE0dhbWVFdmVudEJ1ZmZlclR5cGUSCwoHVU5LTk9XThAAEgoK",
            "BkVOVElUWRABEgwKCFNFQ1VSSVRZEAI="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Redhatgamedev.Srt.EntityGameEventBufferReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Redhatgamedev.Srt.JoinSecurityGameEventBuffer), global::Redhatgamedev.Srt.JoinSecurityGameEventBuffer.Parser, new[]{ "UUID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Redhatgamedev.Srt.LeaveSecurityGameEventBuffer), global::Redhatgamedev.Srt.LeaveSecurityGameEventBuffer.Parser, new[]{ "UUID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Redhatgamedev.Srt.SecurityGameEventBuffer), global::Redhatgamedev.Srt.SecurityGameEventBuffer.Parser, new[]{ "Type", "JoinSecurityGameEventBuffer", "LeaveSecurityGameEventBuffer" }, null, new[]{ typeof(global::Redhatgamedev.Srt.SecurityGameEventBuffer.Types.SecurityGameEventBufferType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Redhatgamedev.Srt.GameEventBuffer), global::Redhatgamedev.Srt.GameEventBuffer.Parser, new[]{ "Type", "EntityGameEventBuffer", "SecurityGameEventBuffer" }, null, new[]{ typeof(global::Redhatgamedev.Srt.GameEventBuffer.Types.GameEventBufferType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class JoinSecurityGameEventBuffer : pb::IMessage<JoinSecurityGameEventBuffer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<JoinSecurityGameEventBuffer> _parser = new pb::MessageParser<JoinSecurityGameEventBuffer>(() => new JoinSecurityGameEventBuffer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<JoinSecurityGameEventBuffer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Redhatgamedev.Srt.GameEventBufferReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JoinSecurityGameEventBuffer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JoinSecurityGameEventBuffer(JoinSecurityGameEventBuffer other) : this() {
      uUID_ = other.uUID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JoinSecurityGameEventBuffer Clone() {
      return new JoinSecurityGameEventBuffer(this);
    }

    /// <summary>Field number for the "UUID" field.</summary>
    public const int UUIDFieldNumber = 1;
    private readonly static string UUIDDefaultValue = "";

    private string uUID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UUID {
      get { return uUID_ ?? UUIDDefaultValue; }
      set {
        uUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "UUID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUUID {
      get { return uUID_ != null; }
    }
    /// <summary>Clears the value of the "UUID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUUID() {
      uUID_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as JoinSecurityGameEventBuffer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(JoinSecurityGameEventBuffer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UUID != other.UUID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasUUID) hash ^= UUID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasUUID) {
        output.WriteRawTag(10);
        output.WriteString(UUID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasUUID) {
        output.WriteRawTag(10);
        output.WriteString(UUID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasUUID) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UUID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(JoinSecurityGameEventBuffer other) {
      if (other == null) {
        return;
      }
      if (other.HasUUID) {
        UUID = other.UUID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UUID = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UUID = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class LeaveSecurityGameEventBuffer : pb::IMessage<LeaveSecurityGameEventBuffer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LeaveSecurityGameEventBuffer> _parser = new pb::MessageParser<LeaveSecurityGameEventBuffer>(() => new LeaveSecurityGameEventBuffer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LeaveSecurityGameEventBuffer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Redhatgamedev.Srt.GameEventBufferReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaveSecurityGameEventBuffer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaveSecurityGameEventBuffer(LeaveSecurityGameEventBuffer other) : this() {
      uUID_ = other.uUID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaveSecurityGameEventBuffer Clone() {
      return new LeaveSecurityGameEventBuffer(this);
    }

    /// <summary>Field number for the "UUID" field.</summary>
    public const int UUIDFieldNumber = 1;
    private readonly static string UUIDDefaultValue = "";

    private string uUID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UUID {
      get { return uUID_ ?? UUIDDefaultValue; }
      set {
        uUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "UUID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUUID {
      get { return uUID_ != null; }
    }
    /// <summary>Clears the value of the "UUID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUUID() {
      uUID_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LeaveSecurityGameEventBuffer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LeaveSecurityGameEventBuffer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UUID != other.UUID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasUUID) hash ^= UUID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasUUID) {
        output.WriteRawTag(10);
        output.WriteString(UUID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasUUID) {
        output.WriteRawTag(10);
        output.WriteString(UUID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasUUID) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UUID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LeaveSecurityGameEventBuffer other) {
      if (other == null) {
        return;
      }
      if (other.HasUUID) {
        UUID = other.UUID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UUID = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UUID = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SecurityGameEventBuffer : pb::IMessage<SecurityGameEventBuffer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SecurityGameEventBuffer> _parser = new pb::MessageParser<SecurityGameEventBuffer>(() => new SecurityGameEventBuffer());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SecurityGameEventBuffer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Redhatgamedev.Srt.GameEventBufferReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SecurityGameEventBuffer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SecurityGameEventBuffer(SecurityGameEventBuffer other) : this() {
      _hasBits0 = other._hasBits0;
      type_ = other.type_;
      joinSecurityGameEventBuffer_ = other.joinSecurityGameEventBuffer_ != null ? other.joinSecurityGameEventBuffer_.Clone() : null;
      leaveSecurityGameEventBuffer_ = other.leaveSecurityGameEventBuffer_ != null ? other.leaveSecurityGameEventBuffer_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SecurityGameEventBuffer Clone() {
      return new SecurityGameEventBuffer(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private readonly static global::Redhatgamedev.Srt.SecurityGameEventBuffer.Types.SecurityGameEventBufferType TypeDefaultValue = global::Redhatgamedev.Srt.SecurityGameEventBuffer.Types.SecurityGameEventBufferType.Unknown;

    private global::Redhatgamedev.Srt.SecurityGameEventBuffer.Types.SecurityGameEventBufferType type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Redhatgamedev.Srt.SecurityGameEventBuffer.Types.SecurityGameEventBufferType Type {
      get { if ((_hasBits0 & 1) != 0) { return type_; } else { return TypeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        type_ = value;
      }
    }
    /// <summary>Gets whether the "type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasType {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearType() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "joinSecurityGameEventBuffer" field.</summary>
    public const int JoinSecurityGameEventBufferFieldNumber = 3;
    private global::Redhatgamedev.Srt.JoinSecurityGameEventBuffer joinSecurityGameEventBuffer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Redhatgamedev.Srt.JoinSecurityGameEventBuffer JoinSecurityGameEventBuffer {
      get { return joinSecurityGameEventBuffer_; }
      set {
        joinSecurityGameEventBuffer_ = value;
      }
    }

    /// <summary>Field number for the "leaveSecurityGameEventBuffer" field.</summary>
    public const int LeaveSecurityGameEventBufferFieldNumber = 4;
    private global::Redhatgamedev.Srt.LeaveSecurityGameEventBuffer leaveSecurityGameEventBuffer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Redhatgamedev.Srt.LeaveSecurityGameEventBuffer LeaveSecurityGameEventBuffer {
      get { return leaveSecurityGameEventBuffer_; }
      set {
        leaveSecurityGameEventBuffer_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SecurityGameEventBuffer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SecurityGameEventBuffer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(JoinSecurityGameEventBuffer, other.JoinSecurityGameEventBuffer)) return false;
      if (!object.Equals(LeaveSecurityGameEventBuffer, other.LeaveSecurityGameEventBuffer)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasType) hash ^= Type.GetHashCode();
      if (joinSecurityGameEventBuffer_ != null) hash ^= JoinSecurityGameEventBuffer.GetHashCode();
      if (leaveSecurityGameEventBuffer_ != null) hash ^= LeaveSecurityGameEventBuffer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (joinSecurityGameEventBuffer_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(JoinSecurityGameEventBuffer);
      }
      if (leaveSecurityGameEventBuffer_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LeaveSecurityGameEventBuffer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (joinSecurityGameEventBuffer_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(JoinSecurityGameEventBuffer);
      }
      if (leaveSecurityGameEventBuffer_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LeaveSecurityGameEventBuffer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (joinSecurityGameEventBuffer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(JoinSecurityGameEventBuffer);
      }
      if (leaveSecurityGameEventBuffer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeaveSecurityGameEventBuffer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SecurityGameEventBuffer other) {
      if (other == null) {
        return;
      }
      if (other.HasType) {
        Type = other.Type;
      }
      if (other.joinSecurityGameEventBuffer_ != null) {
        if (joinSecurityGameEventBuffer_ == null) {
          JoinSecurityGameEventBuffer = new global::Redhatgamedev.Srt.JoinSecurityGameEventBuffer();
        }
        JoinSecurityGameEventBuffer.MergeFrom(other.JoinSecurityGameEventBuffer);
      }
      if (other.leaveSecurityGameEventBuffer_ != null) {
        if (leaveSecurityGameEventBuffer_ == null) {
          LeaveSecurityGameEventBuffer = new global::Redhatgamedev.Srt.LeaveSecurityGameEventBuffer();
        }
        LeaveSecurityGameEventBuffer.MergeFrom(other.LeaveSecurityGameEventBuffer);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Redhatgamedev.Srt.SecurityGameEventBuffer.Types.SecurityGameEventBufferType) input.ReadEnum();
            break;
          }
          case 26: {
            if (joinSecurityGameEventBuffer_ == null) {
              JoinSecurityGameEventBuffer = new global::Redhatgamedev.Srt.JoinSecurityGameEventBuffer();
            }
            input.ReadMessage(JoinSecurityGameEventBuffer);
            break;
          }
          case 34: {
            if (leaveSecurityGameEventBuffer_ == null) {
              LeaveSecurityGameEventBuffer = new global::Redhatgamedev.Srt.LeaveSecurityGameEventBuffer();
            }
            input.ReadMessage(LeaveSecurityGameEventBuffer);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Redhatgamedev.Srt.SecurityGameEventBuffer.Types.SecurityGameEventBufferType) input.ReadEnum();
            break;
          }
          case 26: {
            if (joinSecurityGameEventBuffer_ == null) {
              JoinSecurityGameEventBuffer = new global::Redhatgamedev.Srt.JoinSecurityGameEventBuffer();
            }
            input.ReadMessage(JoinSecurityGameEventBuffer);
            break;
          }
          case 34: {
            if (leaveSecurityGameEventBuffer_ == null) {
              LeaveSecurityGameEventBuffer = new global::Redhatgamedev.Srt.LeaveSecurityGameEventBuffer();
            }
            input.ReadMessage(LeaveSecurityGameEventBuffer);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the SecurityGameEventBuffer message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum SecurityGameEventBufferType {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("JOIN")] Join = 1,
        [pbr::OriginalName("LEAVE")] Leave = 2,
      }

    }
    #endregion

  }

  public sealed partial class GameEventBuffer : pb::IMessage<GameEventBuffer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameEventBuffer> _parser = new pb::MessageParser<GameEventBuffer>(() => new GameEventBuffer());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameEventBuffer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Redhatgamedev.Srt.GameEventBufferReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameEventBuffer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameEventBuffer(GameEventBuffer other) : this() {
      _hasBits0 = other._hasBits0;
      type_ = other.type_;
      entityGameEventBuffer_ = other.entityGameEventBuffer_ != null ? other.entityGameEventBuffer_.Clone() : null;
      securityGameEventBuffer_ = other.securityGameEventBuffer_ != null ? other.securityGameEventBuffer_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameEventBuffer Clone() {
      return new GameEventBuffer(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private readonly static global::Redhatgamedev.Srt.GameEventBuffer.Types.GameEventBufferType TypeDefaultValue = global::Redhatgamedev.Srt.GameEventBuffer.Types.GameEventBufferType.Unknown;

    private global::Redhatgamedev.Srt.GameEventBuffer.Types.GameEventBufferType type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Redhatgamedev.Srt.GameEventBuffer.Types.GameEventBufferType Type {
      get { if ((_hasBits0 & 1) != 0) { return type_; } else { return TypeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        type_ = value;
      }
    }
    /// <summary>Gets whether the "type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasType {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearType() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "entityGameEventBuffer" field.</summary>
    public const int EntityGameEventBufferFieldNumber = 2;
    private global::Redhatgamedev.Srt.EntityGameEventBuffer entityGameEventBuffer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Redhatgamedev.Srt.EntityGameEventBuffer EntityGameEventBuffer {
      get { return entityGameEventBuffer_; }
      set {
        entityGameEventBuffer_ = value;
      }
    }

    /// <summary>Field number for the "securityGameEventBuffer" field.</summary>
    public const int SecurityGameEventBufferFieldNumber = 3;
    private global::Redhatgamedev.Srt.SecurityGameEventBuffer securityGameEventBuffer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Redhatgamedev.Srt.SecurityGameEventBuffer SecurityGameEventBuffer {
      get { return securityGameEventBuffer_; }
      set {
        securityGameEventBuffer_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameEventBuffer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameEventBuffer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(EntityGameEventBuffer, other.EntityGameEventBuffer)) return false;
      if (!object.Equals(SecurityGameEventBuffer, other.SecurityGameEventBuffer)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasType) hash ^= Type.GetHashCode();
      if (entityGameEventBuffer_ != null) hash ^= EntityGameEventBuffer.GetHashCode();
      if (securityGameEventBuffer_ != null) hash ^= SecurityGameEventBuffer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (entityGameEventBuffer_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(EntityGameEventBuffer);
      }
      if (securityGameEventBuffer_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SecurityGameEventBuffer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (entityGameEventBuffer_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(EntityGameEventBuffer);
      }
      if (securityGameEventBuffer_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SecurityGameEventBuffer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (entityGameEventBuffer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EntityGameEventBuffer);
      }
      if (securityGameEventBuffer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SecurityGameEventBuffer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameEventBuffer other) {
      if (other == null) {
        return;
      }
      if (other.HasType) {
        Type = other.Type;
      }
      if (other.entityGameEventBuffer_ != null) {
        if (entityGameEventBuffer_ == null) {
          EntityGameEventBuffer = new global::Redhatgamedev.Srt.EntityGameEventBuffer();
        }
        EntityGameEventBuffer.MergeFrom(other.EntityGameEventBuffer);
      }
      if (other.securityGameEventBuffer_ != null) {
        if (securityGameEventBuffer_ == null) {
          SecurityGameEventBuffer = new global::Redhatgamedev.Srt.SecurityGameEventBuffer();
        }
        SecurityGameEventBuffer.MergeFrom(other.SecurityGameEventBuffer);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Redhatgamedev.Srt.GameEventBuffer.Types.GameEventBufferType) input.ReadEnum();
            break;
          }
          case 18: {
            if (entityGameEventBuffer_ == null) {
              EntityGameEventBuffer = new global::Redhatgamedev.Srt.EntityGameEventBuffer();
            }
            input.ReadMessage(EntityGameEventBuffer);
            break;
          }
          case 26: {
            if (securityGameEventBuffer_ == null) {
              SecurityGameEventBuffer = new global::Redhatgamedev.Srt.SecurityGameEventBuffer();
            }
            input.ReadMessage(SecurityGameEventBuffer);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Redhatgamedev.Srt.GameEventBuffer.Types.GameEventBufferType) input.ReadEnum();
            break;
          }
          case 18: {
            if (entityGameEventBuffer_ == null) {
              EntityGameEventBuffer = new global::Redhatgamedev.Srt.EntityGameEventBuffer();
            }
            input.ReadMessage(EntityGameEventBuffer);
            break;
          }
          case 26: {
            if (securityGameEventBuffer_ == null) {
              SecurityGameEventBuffer = new global::Redhatgamedev.Srt.SecurityGameEventBuffer();
            }
            input.ReadMessage(SecurityGameEventBuffer);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the GameEventBuffer message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum GameEventBufferType {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("ENTITY")] Entity = 1,
        [pbr::OriginalName("SECURITY")] Security = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
