// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RawInputCommandBuffer.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Redhatgamedev.Srt {

  /// <summary>Holder for reflection information generated from RawInputCommandBuffer.proto</summary>
  public static partial class RawInputCommandBufferReflection {

    #region Descriptor
    /// <summary>File descriptor for RawInputCommandBuffer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RawInputCommandBufferReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtSYXdJbnB1dENvbW1hbmRCdWZmZXIucHJvdG8SEXJlZGhhdGdhbWVkZXYu",
            "c3J0GiREdWFsU3RpY2tSYXdJbnB1dENvbW1hbmRCdWZmZXIucHJvdG8iiwIK",
            "FVJhd0lucHV0Q29tbWFuZEJ1ZmZlchJQCgR0eXBlGAEgAigOMkIucmVkaGF0",
            "Z2FtZWRldi5zcnQuUmF3SW5wdXRDb21tYW5kQnVmZmVyLlJhd0lucHV0Q29t",
            "bWFuZEJ1ZmZlclR5cGUSDAoEVVVJRBgCIAIoCRJZCh5kdWFsU3RpY2tSYXdJ",
            "bnB1dENvbW1hbmRCdWZmZXIYAyABKAsyMS5yZWRoYXRnYW1lZGV2LnNydC5E",
            "dWFsU3RpY2tSYXdJbnB1dENvbW1hbmRCdWZmZXIiNwoZUmF3SW5wdXRDb21t",
            "YW5kQnVmZmVyVHlwZRILCgdVTktOT1dOEAASDQoJRFVBTFNUSUNLEAE="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Redhatgamedev.Srt.DualStickRawInputCommandBufferReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Redhatgamedev.Srt.RawInputCommandBuffer), global::Redhatgamedev.Srt.RawInputCommandBuffer.Parser, new[]{ "Type", "UUID", "DualStickRawInputCommandBuffer" }, null, new[]{ typeof(global::Redhatgamedev.Srt.RawInputCommandBuffer.Types.RawInputCommandBufferType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RawInputCommandBuffer : pb::IMessage<RawInputCommandBuffer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RawInputCommandBuffer> _parser = new pb::MessageParser<RawInputCommandBuffer>(() => new RawInputCommandBuffer());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RawInputCommandBuffer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Redhatgamedev.Srt.RawInputCommandBufferReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RawInputCommandBuffer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RawInputCommandBuffer(RawInputCommandBuffer other) : this() {
      _hasBits0 = other._hasBits0;
      type_ = other.type_;
      uUID_ = other.uUID_;
      dualStickRawInputCommandBuffer_ = other.dualStickRawInputCommandBuffer_ != null ? other.dualStickRawInputCommandBuffer_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RawInputCommandBuffer Clone() {
      return new RawInputCommandBuffer(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private readonly static global::Redhatgamedev.Srt.RawInputCommandBuffer.Types.RawInputCommandBufferType TypeDefaultValue = global::Redhatgamedev.Srt.RawInputCommandBuffer.Types.RawInputCommandBufferType.Unknown;

    private global::Redhatgamedev.Srt.RawInputCommandBuffer.Types.RawInputCommandBufferType type_;
    /// <summary>
    /// [default = UNKNOWN];
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Redhatgamedev.Srt.RawInputCommandBuffer.Types.RawInputCommandBufferType Type {
      get { if ((_hasBits0 & 1) != 0) { return type_; } else { return TypeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        type_ = value;
      }
    }
    /// <summary>Gets whether the "type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasType {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearType() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "UUID" field.</summary>
    public const int UUIDFieldNumber = 2;
    private readonly static string UUIDDefaultValue = "";

    private string uUID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UUID {
      get { return uUID_ ?? UUIDDefaultValue; }
      set {
        uUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "UUID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUUID {
      get { return uUID_ != null; }
    }
    /// <summary>Clears the value of the "UUID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUUID() {
      uUID_ = null;
    }

    /// <summary>Field number for the "dualStickRawInputCommandBuffer" field.</summary>
    public const int DualStickRawInputCommandBufferFieldNumber = 3;
    private global::Redhatgamedev.Srt.DualStickRawInputCommandBuffer dualStickRawInputCommandBuffer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Redhatgamedev.Srt.DualStickRawInputCommandBuffer DualStickRawInputCommandBuffer {
      get { return dualStickRawInputCommandBuffer_; }
      set {
        dualStickRawInputCommandBuffer_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RawInputCommandBuffer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RawInputCommandBuffer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (UUID != other.UUID) return false;
      if (!object.Equals(DualStickRawInputCommandBuffer, other.DualStickRawInputCommandBuffer)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasType) hash ^= Type.GetHashCode();
      if (HasUUID) hash ^= UUID.GetHashCode();
      if (dualStickRawInputCommandBuffer_ != null) hash ^= DualStickRawInputCommandBuffer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (HasUUID) {
        output.WriteRawTag(18);
        output.WriteString(UUID);
      }
      if (dualStickRawInputCommandBuffer_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DualStickRawInputCommandBuffer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (HasUUID) {
        output.WriteRawTag(18);
        output.WriteString(UUID);
      }
      if (dualStickRawInputCommandBuffer_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DualStickRawInputCommandBuffer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (HasUUID) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UUID);
      }
      if (dualStickRawInputCommandBuffer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DualStickRawInputCommandBuffer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RawInputCommandBuffer other) {
      if (other == null) {
        return;
      }
      if (other.HasType) {
        Type = other.Type;
      }
      if (other.HasUUID) {
        UUID = other.UUID;
      }
      if (other.dualStickRawInputCommandBuffer_ != null) {
        if (dualStickRawInputCommandBuffer_ == null) {
          DualStickRawInputCommandBuffer = new global::Redhatgamedev.Srt.DualStickRawInputCommandBuffer();
        }
        DualStickRawInputCommandBuffer.MergeFrom(other.DualStickRawInputCommandBuffer);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Redhatgamedev.Srt.RawInputCommandBuffer.Types.RawInputCommandBufferType) input.ReadEnum();
            break;
          }
          case 18: {
            UUID = input.ReadString();
            break;
          }
          case 26: {
            if (dualStickRawInputCommandBuffer_ == null) {
              DualStickRawInputCommandBuffer = new global::Redhatgamedev.Srt.DualStickRawInputCommandBuffer();
            }
            input.ReadMessage(DualStickRawInputCommandBuffer);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Redhatgamedev.Srt.RawInputCommandBuffer.Types.RawInputCommandBufferType) input.ReadEnum();
            break;
          }
          case 18: {
            UUID = input.ReadString();
            break;
          }
          case 26: {
            if (dualStickRawInputCommandBuffer_ == null) {
              DualStickRawInputCommandBuffer = new global::Redhatgamedev.Srt.DualStickRawInputCommandBuffer();
            }
            input.ReadMessage(DualStickRawInputCommandBuffer);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the RawInputCommandBuffer message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum RawInputCommandBufferType {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("DUALSTICK")] Dualstick = 1,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
