// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SecurityCommandBuffer.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Redhatgamedev.Srt {

  /// <summary>Holder for reflection information generated from SecurityCommandBuffer.proto</summary>
  public static partial class SecurityCommandBufferReflection {

    #region Descriptor
    /// <summary>File descriptor for SecurityCommandBuffer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SecurityCommandBufferReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtTZWN1cml0eUNvbW1hbmRCdWZmZXIucHJvdG8SEXJlZGhhdGdhbWVkZXYu",
            "c3J0IhsKGUpvaW5TZWN1cml0eUNvbW1hbmRCdWZmZXIiKgoaTGVhdmVTZWN1",
            "cml0eUNvbW1hbmRCdWZmZXISDAoEVVVJRBgBIAIoCSLaAgoVU2VjdXJpdHlD",
            "b21tYW5kQnVmZmVyElAKBHR5cGUYASACKA4yQi5yZWRoYXRnYW1lZGV2LnNy",
            "dC5TZWN1cml0eUNvbW1hbmRCdWZmZXIuU2VjdXJpdHlDb21tYW5kQnVmZmVy",
            "VHlwZRIMCgRVVUlEGAIgASgJEk8KGWpvaW5TZWN1cml0eUNvbW1hbmRCdWZm",
            "ZXIYAyABKAsyLC5yZWRoYXRnYW1lZGV2LnNydC5Kb2luU2VjdXJpdHlDb21t",
            "YW5kQnVmZmVyElEKGmxlYXZlU2VjdXJpdHlDb21tYW5kQnVmZmVyGAQgASgL",
            "Mi0ucmVkaGF0Z2FtZWRldi5zcnQuTGVhdmVTZWN1cml0eUNvbW1hbmRCdWZm",
            "ZXIiPQoZU2VjdXJpdHlDb21tYW5kQnVmZmVyVHlwZRILCgdVTktOT1dOEAAS",
            "CAoESk9JThABEgkKBUxFQVZFEAI="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Redhatgamedev.Srt.JoinSecurityCommandBuffer), global::Redhatgamedev.Srt.JoinSecurityCommandBuffer.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Redhatgamedev.Srt.LeaveSecurityCommandBuffer), global::Redhatgamedev.Srt.LeaveSecurityCommandBuffer.Parser, new[]{ "UUID" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Redhatgamedev.Srt.SecurityCommandBuffer), global::Redhatgamedev.Srt.SecurityCommandBuffer.Parser, new[]{ "Type", "UUID", "JoinSecurityCommandBuffer", "LeaveSecurityCommandBuffer" }, null, new[]{ typeof(global::Redhatgamedev.Srt.SecurityCommandBuffer.Types.SecurityCommandBufferType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class JoinSecurityCommandBuffer : pb::IMessage<JoinSecurityCommandBuffer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<JoinSecurityCommandBuffer> _parser = new pb::MessageParser<JoinSecurityCommandBuffer>(() => new JoinSecurityCommandBuffer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<JoinSecurityCommandBuffer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Redhatgamedev.Srt.SecurityCommandBufferReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JoinSecurityCommandBuffer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JoinSecurityCommandBuffer(JoinSecurityCommandBuffer other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public JoinSecurityCommandBuffer Clone() {
      return new JoinSecurityCommandBuffer(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as JoinSecurityCommandBuffer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(JoinSecurityCommandBuffer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(JoinSecurityCommandBuffer other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class LeaveSecurityCommandBuffer : pb::IMessage<LeaveSecurityCommandBuffer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LeaveSecurityCommandBuffer> _parser = new pb::MessageParser<LeaveSecurityCommandBuffer>(() => new LeaveSecurityCommandBuffer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LeaveSecurityCommandBuffer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Redhatgamedev.Srt.SecurityCommandBufferReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaveSecurityCommandBuffer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaveSecurityCommandBuffer(LeaveSecurityCommandBuffer other) : this() {
      uUID_ = other.uUID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LeaveSecurityCommandBuffer Clone() {
      return new LeaveSecurityCommandBuffer(this);
    }

    /// <summary>Field number for the "UUID" field.</summary>
    public const int UUIDFieldNumber = 1;
    private readonly static string UUIDDefaultValue = "";

    private string uUID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UUID {
      get { return uUID_ ?? UUIDDefaultValue; }
      set {
        uUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "UUID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUUID {
      get { return uUID_ != null; }
    }
    /// <summary>Clears the value of the "UUID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUUID() {
      uUID_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LeaveSecurityCommandBuffer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LeaveSecurityCommandBuffer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UUID != other.UUID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasUUID) hash ^= UUID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasUUID) {
        output.WriteRawTag(10);
        output.WriteString(UUID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasUUID) {
        output.WriteRawTag(10);
        output.WriteString(UUID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasUUID) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UUID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LeaveSecurityCommandBuffer other) {
      if (other == null) {
        return;
      }
      if (other.HasUUID) {
        UUID = other.UUID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UUID = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UUID = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SecurityCommandBuffer : pb::IMessage<SecurityCommandBuffer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SecurityCommandBuffer> _parser = new pb::MessageParser<SecurityCommandBuffer>(() => new SecurityCommandBuffer());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SecurityCommandBuffer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Redhatgamedev.Srt.SecurityCommandBufferReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SecurityCommandBuffer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SecurityCommandBuffer(SecurityCommandBuffer other) : this() {
      _hasBits0 = other._hasBits0;
      type_ = other.type_;
      uUID_ = other.uUID_;
      joinSecurityCommandBuffer_ = other.joinSecurityCommandBuffer_ != null ? other.joinSecurityCommandBuffer_.Clone() : null;
      leaveSecurityCommandBuffer_ = other.leaveSecurityCommandBuffer_ != null ? other.leaveSecurityCommandBuffer_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SecurityCommandBuffer Clone() {
      return new SecurityCommandBuffer(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private readonly static global::Redhatgamedev.Srt.SecurityCommandBuffer.Types.SecurityCommandBufferType TypeDefaultValue = global::Redhatgamedev.Srt.SecurityCommandBuffer.Types.SecurityCommandBufferType.Unknown;

    private global::Redhatgamedev.Srt.SecurityCommandBuffer.Types.SecurityCommandBufferType type_;
    /// <summary>
    ///required SecurityCommandBufferType type = 1 [default = UNKNOWN];
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Redhatgamedev.Srt.SecurityCommandBuffer.Types.SecurityCommandBufferType Type {
      get { if ((_hasBits0 & 1) != 0) { return type_; } else { return TypeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        type_ = value;
      }
    }
    /// <summary>Gets whether the "type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasType {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearType() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "UUID" field.</summary>
    public const int UUIDFieldNumber = 2;
    private readonly static string UUIDDefaultValue = "";

    private string uUID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UUID {
      get { return uUID_ ?? UUIDDefaultValue; }
      set {
        uUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "UUID" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUUID {
      get { return uUID_ != null; }
    }
    /// <summary>Clears the value of the "UUID" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUUID() {
      uUID_ = null;
    }

    /// <summary>Field number for the "joinSecurityCommandBuffer" field.</summary>
    public const int JoinSecurityCommandBufferFieldNumber = 3;
    private global::Redhatgamedev.Srt.JoinSecurityCommandBuffer joinSecurityCommandBuffer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Redhatgamedev.Srt.JoinSecurityCommandBuffer JoinSecurityCommandBuffer {
      get { return joinSecurityCommandBuffer_; }
      set {
        joinSecurityCommandBuffer_ = value;
      }
    }

    /// <summary>Field number for the "leaveSecurityCommandBuffer" field.</summary>
    public const int LeaveSecurityCommandBufferFieldNumber = 4;
    private global::Redhatgamedev.Srt.LeaveSecurityCommandBuffer leaveSecurityCommandBuffer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Redhatgamedev.Srt.LeaveSecurityCommandBuffer LeaveSecurityCommandBuffer {
      get { return leaveSecurityCommandBuffer_; }
      set {
        leaveSecurityCommandBuffer_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SecurityCommandBuffer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SecurityCommandBuffer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (UUID != other.UUID) return false;
      if (!object.Equals(JoinSecurityCommandBuffer, other.JoinSecurityCommandBuffer)) return false;
      if (!object.Equals(LeaveSecurityCommandBuffer, other.LeaveSecurityCommandBuffer)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasType) hash ^= Type.GetHashCode();
      if (HasUUID) hash ^= UUID.GetHashCode();
      if (joinSecurityCommandBuffer_ != null) hash ^= JoinSecurityCommandBuffer.GetHashCode();
      if (leaveSecurityCommandBuffer_ != null) hash ^= LeaveSecurityCommandBuffer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (HasUUID) {
        output.WriteRawTag(18);
        output.WriteString(UUID);
      }
      if (joinSecurityCommandBuffer_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(JoinSecurityCommandBuffer);
      }
      if (leaveSecurityCommandBuffer_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LeaveSecurityCommandBuffer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (HasUUID) {
        output.WriteRawTag(18);
        output.WriteString(UUID);
      }
      if (joinSecurityCommandBuffer_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(JoinSecurityCommandBuffer);
      }
      if (leaveSecurityCommandBuffer_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LeaveSecurityCommandBuffer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (HasUUID) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UUID);
      }
      if (joinSecurityCommandBuffer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(JoinSecurityCommandBuffer);
      }
      if (leaveSecurityCommandBuffer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeaveSecurityCommandBuffer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SecurityCommandBuffer other) {
      if (other == null) {
        return;
      }
      if (other.HasType) {
        Type = other.Type;
      }
      if (other.HasUUID) {
        UUID = other.UUID;
      }
      if (other.joinSecurityCommandBuffer_ != null) {
        if (joinSecurityCommandBuffer_ == null) {
          JoinSecurityCommandBuffer = new global::Redhatgamedev.Srt.JoinSecurityCommandBuffer();
        }
        JoinSecurityCommandBuffer.MergeFrom(other.JoinSecurityCommandBuffer);
      }
      if (other.leaveSecurityCommandBuffer_ != null) {
        if (leaveSecurityCommandBuffer_ == null) {
          LeaveSecurityCommandBuffer = new global::Redhatgamedev.Srt.LeaveSecurityCommandBuffer();
        }
        LeaveSecurityCommandBuffer.MergeFrom(other.LeaveSecurityCommandBuffer);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Redhatgamedev.Srt.SecurityCommandBuffer.Types.SecurityCommandBufferType) input.ReadEnum();
            break;
          }
          case 18: {
            UUID = input.ReadString();
            break;
          }
          case 26: {
            if (joinSecurityCommandBuffer_ == null) {
              JoinSecurityCommandBuffer = new global::Redhatgamedev.Srt.JoinSecurityCommandBuffer();
            }
            input.ReadMessage(JoinSecurityCommandBuffer);
            break;
          }
          case 34: {
            if (leaveSecurityCommandBuffer_ == null) {
              LeaveSecurityCommandBuffer = new global::Redhatgamedev.Srt.LeaveSecurityCommandBuffer();
            }
            input.ReadMessage(LeaveSecurityCommandBuffer);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Redhatgamedev.Srt.SecurityCommandBuffer.Types.SecurityCommandBufferType) input.ReadEnum();
            break;
          }
          case 18: {
            UUID = input.ReadString();
            break;
          }
          case 26: {
            if (joinSecurityCommandBuffer_ == null) {
              JoinSecurityCommandBuffer = new global::Redhatgamedev.Srt.JoinSecurityCommandBuffer();
            }
            input.ReadMessage(JoinSecurityCommandBuffer);
            break;
          }
          case 34: {
            if (leaveSecurityCommandBuffer_ == null) {
              LeaveSecurityCommandBuffer = new global::Redhatgamedev.Srt.LeaveSecurityCommandBuffer();
            }
            input.ReadMessage(LeaveSecurityCommandBuffer);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the SecurityCommandBuffer message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum SecurityCommandBufferType {
        [pbr::OriginalName("UNKNOWN")] Unknown = 0,
        [pbr::OriginalName("JOIN")] Join = 1,
        [pbr::OriginalName("LEAVE")] Leave = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
